### ISSUE TITLE
Investigate CSV storage options

### ISSUE THREAD

**Issue by michaelkunc** [foodoasisla/backend#41]
Currently files are stored in google drive as sheets. We will need to access these files to put them into the Postgres database. Currently the csv_ingest file is looking for the files to be stored locally. 

Can we grab the data directly from google sheets? Should we move it to Amazon S3? Is storing the locally the best option?

@rebeccapizano -> Is this something you'd be able to take a look at?

**Comment by rebeccapizano** [comment]
Oh this is a neat message board, I almost missed this. I don't know what Amazon S3 is, but I will look into it.

**Comment by michaelkunc** [comment]
Going to close the issue. Plan is to host the files on github during the initial ingest.
